### ISSUE TITLE
BAD_ACCESS crash

### ISSUE THREAD

**Issue by marioizquierdo** [life360/confetti#12]
Sometimes the confetti animation crashes because of a memory bad access issue.

It happens on `needToDeallocateConfettiObject`, when the confetti object is doing `cleanupObject`. I think the issue is that the `L360ConfettiArea` has the property `confettiObjectsCache` being accessed from multiple threads, and it's usually not a good idea to modify a NSMutableArray from multiple threads.

I fixed the problem on my own project by modifying the `burstAt` method to not spawn confetti in a background thread and just do everything on the main thread. For my case there's no performance penalty whatsoever (I do 6 different 15-25 confetti bursts only).

Maybe `burstAt` and `blastFrom` should not use background threads? Maybe the `confettiObjectsCache` is not needed after all?

**Comment by iSpartak** [comment]
thanks for the hint, marioizquierdo. Had to do the same to fix BAD_ACCESS issue. On my side it crashed on 

[weakSelf.confettiObjectsCache addObject:confettiObject];

**Comment by mding5692** [comment]
Hi how did you guys move it to the main thread? Just wondering because Im getting the same issue

**Comment by mding5692** [comment]
I noticed there was some differences in how the confetti moved down as pointed out by a friend when using this in my app. Moved the code mentioned by @iSpartak into the main thread and seemed to resolve no crashing and maintain the same falling pattern.

**Comment by marioizquierdo** [comment]
@mdin
